services:
  - type: web
    name: github-stats-svg-api
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    runtime: python-3.11.9
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: REDIS_URL
        value: redis://localhost:6379/0
      - key: PORT
        value: 8000
    autoDeploy: false
    healthCheckPath: /
    disk:
      name: github-stats-data
      mountPath: /data
      sizeGB: 1
